---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: ljfranklin/terraform-resource
    tag: dev

inputs:
- name: resource-src

run:
  path: resource-src/scripts/run-tests

params:
  AWS_ACCESS_KEY:           ""
  AWS_SECRET_KEY:           ""
  AWS_BUCKET:               ""
  AWS_BUCKET_SUBFOLDER:     ""
  GCS_BUCKET:               ""
  GCS_ENDPOINT:             ""
  GCS_ACCESS_KEY:           ""
  GCS_SECRET_KEY:           ""
  GCS_CREDENTIALS_JSON:     ""
  S3_KMS_KEY_ID:            ""
  GITHUB_PRIVATE_KEY:       ""
